import Header from "components/Header"
import "../../styles/globals.css"
import Banner from "components/Banner"
import Footer from "components/Footer"

export const metadata = {
  title: 'Radiant Pulse',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="max-w-7xl mx-auto">
        <link rel="icon" href="/rap.png"  />
      <Header/>
      <Banner/>
        {children}
        <Footer/>
      
      </body>
    </html>
  )
}
