import Header from "components/Header";
import "../../styles/globals.css";
import Banner from "components/Banner";
import Footer from "components/Footer";
import Providers from "components/Providers";

export const metadata = {
  title: "Radiant Pulse",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="max-w-7xl mx-auto scroll-smooth">
        <Providers>
      <link rel="icon" href="/icon.png" />
        <Header />
        <Banner />
        <div className="relative min-h-screen">{children}</div>
        <div className="position-fixed">
          <hr className="border-[#0A7DFF]"/>
          <Footer />
        </div>
        </Providers>
      </body>
    </html>
  );
}
